# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('scheduler_type', models.PositiveSmallIntegerField(choices=[(0, 'One-Time Date/Time'), (1, 'Recurrence Date/Time'), (2, 'Specific Date/Time')], default=1)),
                ('start_type', models.PositiveSmallIntegerField(choices=[(0, 'Certain Start/Stop Time'), (1, 'Period Lifetime')], default=0)),
                ('start_time', models.TimeField(blank=True, help_text='start time', null=True)),
                ('stop_time', models.TimeField(blank=True, help_text='stop time', null=True)),
                ('month_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('weekday_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('schedule_days', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('stop_type', models.PositiveSmallIntegerField(choices=[(0, 'date/time'), (1, 'period')], default=0)),
                ('lifetime_quantity', models.PositiveSmallIntegerField(default=0)),
                ('lifetime_unit', models.PositiveSmallIntegerField(choices=[(0, 'Minutes'), (1, 'Hours'), (2, 'Days')], default=0)),
            ],
        ),
    ]
