# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 04:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_planner_test_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='month_day',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='test_json',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='url',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='week_day',
        ),
        migrations.AddField(
            model_name='planner',
            name='date_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='month_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='scheduler_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'One-Time Date/Time'), (1, 'Recurrence Date/Time'), (2, 'Specific Date/Time')], default=1),
        ),
        migrations.AddField(
            model_name='planner',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='start_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Certain Start/Stop Time'), (1, 'Period Lifetime')], default=0),
        ),
        migrations.AddField(
            model_name='planner',
            name='stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='weekday_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
