# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20160428_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='name',
        ),
        migrations.AlterField(
            model_name='planner',
            name='start_time',
            field=models.TimeField(blank=True, help_text='start time', null=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='stop_time',
            field=models.TimeField(blank=True, help_text='stop time', null=True),
        ),
    ]
